# Generated by Django 4.2.9 on 2024-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
